### ISSUE TITLE
git管理について

### ISSUE THREAD

**Issue by yumemi-kuwahara** [vam0718/Unity-BomberMan#2]
* `.gitignore`を作成した方が良いです（以下例）

```git
Library
Temp
*.bat
```

**Comment by vam0718** [comment]
＠kuwaharaさん
ご教授ありがとうございます

＠shinji19さん
作成ありがとうございます💦

**Comment by yumemi-kuwahara** [comment]
@vam0718 
そのままマージされたので、プルするとアプリが動かなくなると思います。

**Comment by vam0718** [comment]
@yumemi-kuwahara
コメントありがとうございます。 
プルしてますが、今のところは動かなくなるということはないです
